defaults:
  - model:
  - metrics: inference_metrics
  - datasets: infernce_dataset # we do not want to run inference on training data
  - dataloader: example
  - transforms: example_only_instance
  - _self_
inferencer:
  device_tensors: ['s1_spectrogram', 's2_spectrogram', 'mix_spectrogram', 's1_audio', 's2_audio', 'mix_audio', 's1_embs', 's2_embs'] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/exp_name/model_best.pth" # path to the pretrained model
  dataset_link:
  dataset_path:
